package aurora.plugin.esb.model;

public interface TaskStatus {

	String STARTING = "STARTING";

	String FEEDBACKED = "FEEDBACKED";

	String SERVER_DATA_LOADED = "SERVER_DATA_LOADED";
	String SERVER_WORK_FINISH = "SERVER_WORK_FINISH";
	String DATA_SAVED = "DATA_SAVED";
	String INVOKE_CLIENT_POINT = "INVOKE_CLIENT_POINT";
	String CLIENT_RESPONSED = "CLIENT_RESPONSED";

	String CLIENT_RESPONSED_SAVED = "CLIENT_RESPONSED_SAVED";

	String STOPED = "STOPED";
	String FINISH = "FINISH";

	String ERROR_ON_STARTING = "ERROR_ON_STARTING";
}
